# extras/wezterm/oasis_abyss_dark.toml
## name: Oasis Abyss Dark
## author: uhs-robert

[colors]
foreground = "#F0EBE6"
background= "#000000"
cursor_bg = "#F0E68C"
cursor_border = "#F0E68C"
cursor_fg= "#000000"
selection_bg= "#532E2E"
selection_fg= "#000000"
split= "#D06666"
compose_cursor= "#FF8A1F"
scrollbar_thumb= "#1A1A1A"
visual_bell= "#080808"

ansi = [
  '#000000',
  '#D06666',
  '#53D390',
  '#F0E68C',
  '#519BFF',
  '#C28EFF',
  '#5ABAAE',
  '#DDDBD5',
]

brights = [
  '#666666',
  '#FFA0A0',
  '#96EA7F',
  '#FFA247',
  '#87CEEB',
  '#D2ADFF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FF8A1F'
17 = '#CDC673'

[colors.tab_bar]
background = '#080808'
inactive_tab_edge = '#050505'

[colors.tab_bar.active_tab]
bg_color = '#D06666'
fg_color = '#000000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#1A1A1A'
fg_color = '#D06666'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#1A1A1A'
fg_color = '#FFA247'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#FFA247'
fg_color = '#000000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#81C0B6'
fg_color = '#000000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Abyss Dark'
