[colors]
ansi = [
    "#1f2335",
    "#f7768e",
    "#9cd58a",
    "#e6c384",
    "#7a88cf",
    "#d7729f",
    "#7bb0c0",
    "#8289a6",
]
background = "#1f2335"
brights = [
    "#545c7e",
    "#f7768e",
    "#9cd58a",
    "#e6c384",
    "#7a88cf",
    "#d7729f",
    "#7bb0c0",
    "#a9b1d6",
]
cursor_bg = "#a9b1d6"
cursor_border = "#a9b1d6"
cursor_fg = "#1f2335"
foreground = "#a9b1d6"
selection_bg = "#4b517a"
selection_fg = "#a9b1d6"

[colors.indexed]

[colors.tab_bar]
background = "#1a1e30"
inactive_tab_edge = "#1f2335"

[colors.tab_bar.active_tab]
bg_color = "#1f2335"
fg_color = "#7a88cf"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#1a1e30"
fg_color = "#545c7e"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1a1e30"
fg_color = "#7a88cf"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#1a1e30"
fg_color = "#7a88cf"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#7a88cf"
fg_color = "#1f2335"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
author = "folke (Moon Adapted)"
name = "TokyoNight-Moon"
