[colors]
ansi = [
    "#f2e9e1",
    "#b4637a",
    "#56949f",
    "#ea9d34",
    "#286983",
    "#907aa9",
    "#d7827e",
    "#575279",
]
background = "#faf4ed"
brights = [
    "#9893a5",
    "#b4637a",
    "#56949f",
    "#ea9d34",
    "#286983",
    "#907aa9",
    "#d7827e",
    "#575279",
]
cursor_bg = "#797593"
cursor_border = "#797593"
cursor_fg = "#faf4ed"
foreground = "#575279"
selection_bg = "#dfdad9"
selection_fg = "#575279"

[colors.indexed]

[metadata]
name = "Noctalia"
