[colors]
ansi = [
    "#393552",
    "#eb6f92",
    "#9ccfd8",
    "#f6c177",
    "#3e8fb0",
    "#c4a7e7",
    "#ea9a97",
    "#e0def4",
]
background = "#232136"
brights = [
    "#6e6a86",
    "#eb6f92",
    "#9ccfd8",
    "#f6c177",
    "#3e8fb0",
    "#c4a7e7",
    "#ea9a97",
    "#e0def4",
]
cursor_bg = "#908caa"
cursor_border = "#908caa"
cursor_fg = "#e0def4"
foreground = "#e0def4"
selection_bg = "#44415a"
selection_fg = "#e0def4"

[colors.indexed]

[metadata]
name = "Noctalia"
