[colors]
ansi = [
    "#0c0e14",
    "#e64572",
    "#89d36a",
    "#d7a23a",
    "#4f8fff",
    "#9d6dff",
    "#43c9ff",
    "#b7c4f2",
]

background = "#2A1922"
foreground = "#F3C7D7"

brights = [
    "#2b314a",
    "#e64572",
    "#89d36a",
    "#d7a23a",
    "#4f8fff",
    "#9d6dff",
    "#43c9ff",
    "#d8e0ff",
]

cursor_bg = "#EFDCE8"
cursor_border = "#EFDCE8"
cursor_fg = "#2A1B21"

selection_bg = "#F2C1D4"
selection_fg = "#2A1B21"

[metadata]
name = "Noctalia"
