[colors]
ansi = [
    "#e9e9ed",
    "#f52a65",
    "#587539",
    "#8c6c3e",
    "#2e7de9",
    "#9854f1",
    "#007197",
    "#6172b0",
]

background = "#F7E6EE"
foreground = "#2A1B21"

brights = [
    "#a1a6c5",
    "#f52a65",
    "#587539",
    "#8c6c3e",
    "#2e7de9",
    "#9854f1",
    "#007197",
    "#3760bf",
]

cursor_bg = "#6F4E63"
cursor_border = "#6F4E63"
cursor_fg = "#F7E2EB"

selection_bg = "#F9EDF3"
selection_fg = "#2A1B21"

[metadata]
name = "Noctalia"
