[colors]
ansi = ["#000000","#ff99b8","#ffccdd","#ffcce0","#ff8cb3","#ffb3cc","#ffd6e8","#ffe0eb"]
background = "#000000"
brights = ["#5a3f4d","#ffb8cc","#ffd6e8","#ffe0f0","#ffa8c2","#ffccdd","#ffe8f2","#fff0f5"]
cursor_bg = "#ffe0eb"
cursor_border = "#ffe0eb"
cursor_fg = "#000000"
foreground = "#ffe0eb"
selection_bg = "#5a3f4d"
selection_fg = "#ffe0eb"

[metadata]
name = "RoseyAMOLED (Dark)"
