[colors.primary]
background = '#101510'
foreground = '#dfe4dc'
 
[colors.cursor]
text = '#dfe4dc'
cursor = '#c1c9be' 
 
[colors.vi_mode_cursor]
text = '#101510'
cursor = '#9ad4a1' 
 
[colors.search.matches]
foreground = '#414941' 
background = '#a1ced8' 
 
[colors.search.focused_match]
foreground = '#414941' 
background = '#9ad4a1' 
 
[colors.footer_bar]
foreground = '#414941' 
background = '#dfe4dc' 
 
[colors.hints.start]
foreground = '#414941' 
background = '#b7ccb6' 
 
[colors.hints.end]
foreground = '#414941' 
background = '#b7ccb6' 
 
[colors.selection]
text = '#101510'
background = '#9ad4a1'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#9ad4a1' 
yellow = '#346940' 
blue = '#9ad4a1' 
magenta = '#a1ced8' 
cyan = '#b7ccb6' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 