[colors]
ansi = [
    "#f6fbf2",
    "#ba1a1a",
    "#39656d",
    "#506351",
    "#346940",
    "#a1ced8",
    "#b7ccb6",
    "#181d18",
]
background = "#f6fbf2"
brights = [
    "#727970",
    "#ba1a1a",
    "#39656d",
    "#506351",
    "#346940",
    "#a1ced8",
    "#b7ccb6",
    "#181d18",
]
cursor_bg = "#181d18"
cursor_border = "#181d18"
cursor_fg = "#f6fbf2"
foreground = "#181d18"
selection_bg = "#dde5da"
selection_fg = "#414941"

[metadata]
name = "Noctalia"
