[colors]
ansi = [
    "#525252",
    "#ee5396",
    "#42be65",
    "#ffab91",
    "#0f62fe",
    "#be95ff",
    "#08bdba",
    "#ffffff",
]
background = "#f2f4f8"
brights = [
    "#161616",
    "#ff7eb6",
    "#42be65",
    "#ffab91",
    "#0f62fe",
    "#673ab7",
    "#08bdba",
    "#f2f2f2",
]
cursor_bg = "#161616"
cursor_border = "#161616"
cursor_fg = "#f2f4f8"
foreground = "#161616"
selection_bg = "#0f62fe"
selection_fg = "#f2f4f8"

[metadata]
name = "Noctalia"
