[colors]
ansi = [
    "#262626",
    "#ee5396",
    "#42be65",
    "#82cfff",
    "#33b1ff",
    "#ff7eb6",
    "#3ddbd9",
    "#dde1e6",
]
background = "#161616"
brights = [
    "#393939",
    "#ee5396",
    "#42be65",
    "#82cfff",
    "#33b1ff",
    "#ff7eb6",
    "#3ddbd9",
    "#ffffff",
]
cursor_bg = "#f2f4f8"
cursor_border = "#f2f4f8"
cursor_fg = "#161616"
foreground = "#f2f4f8"
selection_bg = "#f2f4f8"
selection_fg = "#161616"

[metadata]
name = "Noctalia"
